### ISSUE TITLE
并发高（1分钟600次），出现错误JobResult:System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by neil-he** [yuzd/Hangfire.HttpJob#10]
错误如下所示：
+43ms   HttpStatusCode:OK
+47ms   JobResult:System.NullReferenceException: Object reference not set to an instance of an object.
   at Hangfire.HttpJob.Agent.JobAgentMiddleware.<>c.<InvokeAsync>b__5_1(JobAgent r)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hangfire.HttpJob.Agent.JobAgentMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next)
+54msJobEnd:2019-07-06 22:00:18

**Comment by yuzd** [comment]
你的是单例的job还是多例的？

**Comment by yuzd** [comment]
我修复了 请更新成最新的agent 试试

**Comment by neil-he** [comment]
多例的job，好的 谢谢哈

**Comment by yuzd** [comment]
你在帮忙测试试试看 有问题再call我

**Comment by neil-he** [comment]
> 你在帮忙测试试试看 有问题再call我

嗯嗯，试了40分钟，没有问题了

**Comment by yuzd** [comment]
多谢
