### ISSUE TITLE
RedisHangfire生产环境运行半天后，把整个IIS给整坏了

### ISSUE THREAD

**Issue by zxingdream** [yuzd/Hangfire.HttpJob#163]
具体错误信息如下（windows日志查询到的）：
 Application: w3wp.exe
CoreCLR Version: 5.0.1522.11506
.NET Version: 5.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more hosted services failed to stop. (The operation was canceled.)
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Hangfire.Processing.TaskExtensions.WaitOneAsync(WaitHandle waitHandle, TimeSpan timeout, CancellationToken token)
   at Hangfire.Processing.BackgroundDispatcher.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Hangfire.Server.BackgroundProcessingServer.WaitForShutdownAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at AutoJob.Program.Main(String[] args) in E:\WrokStation\BsShop\Develop\NET5\AutoJob\Program.cs:line 16

  httpjob版本3.7 ，

**Comment by zxingdream** [comment]
项目是参考demo里面的 Redis下面的 RedisHangfire ，我重新建了一个5.0的webapi项目，

**Comment by yuzd** [comment]
这个错误 无法判断是什么原因
